name: Run it

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      stupidInput:
        description: 'Show me the reason'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Run it
      run: python dumper.py

    - name: Upload log file to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: decompiled-scripts-dumper
        path: decompiled-scripts-dumper.log
